import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Info, RotateCcw, ExternalLink, Syringe, QrCode, ArrowLeft, FlaskConical, Microscope, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { motion } from 'framer-motion';
import SEO from '@/components/SEO';
import { QRCodeSVG } from 'qrcode.react';
import { Dialog, DialogContent } from '@/components/ui/dialog';

export default function PeptideCalculator() {
  const [dose, setDose] = useState('1');
  const [doseCustom, setDoseCustom] = useState('');
  const [strength, setStrength] = useState('10');
  const [strengthCustom, setStrengthCustom] = useState('');
  const [water, setWater] = useState('1.0');
  const [waterCustom, setWaterCustom] = useState('');
  const [syringeSize, setSyringeSize] = useState('1'); // '1', '2', or '3' mL
  const [showQRCode, setShowQRCode] = useState(false);

  // Fetch products
  const { data: products = [] } = useQuery({
    queryKey: ['products'],
    queryFn: () => base44.entities.Product.list(),
  });

  const doseOptions = ['0.1', '0.25', '0.5', '1', '2.5', '5', '7.5', '10', '12.5', '15', '50'];
  const strengthOptions = ['1', '5', '10', '15', '20', '30', '50', '1000'];
  const waterOptions = ['1.0', '2.0', '3.0'];
  const syringeSizeOptions = [
    { value: '1', label: '1 mL Syringe (100 units)', units: 100 },
    { value: '2', label: '2 mL Syringe (200 units)', units: 200 },
    { value: '3', label: '3 mL Syringe (300 units)', units: 300 }
  ];

  const currentDose = dose === 'other' ? parseFloat(doseCustom) || 0 : parseFloat(dose);
  const currentStrength = strength === 'other' ? parseFloat(strengthCustom) || 0 : parseFloat(strength);
  const currentWater = water === 'other' ? parseFloat(waterCustom) || 0 : parseFloat(water);
  const currentSyringeSize = parseFloat(syringeSize);
  const totalSyringeUnits = currentSyringeSize * 100; // 100 units per mL

  const concentration = currentWater > 0 ? currentStrength / currentWater : 0;
  const drawAmountML = concentration > 0 ? (currentDose / concentration) : 0;
  const drawAmount = drawAmountML.toFixed(3);
  // Units are always 100 per mL regardless of syringe size
  const drawUnits = concentration > 0 ? (drawAmountML * 100).toFixed(0) : 0;
  const dosesInVial = concentration > 0 && currentDose > 0 ? Math.floor(currentStrength / currentDose) : 0;

  const isValid = currentDose > 0 && currentStrength > 0 && currentWater > 0;

  // Check if draw exceeds syringe capacity
  const exceedsSyringeCapacity = drawAmountML > currentSyringeSize;

  const handleReset = () => {
    setDose('1');
    setDoseCustom('');
    setStrength('10');
    setStrengthCustom('');
    setWater('1.0');
    setWaterCustom('');
    setSyringeSize('1');
  };

  const handleDownload = () => {
    const timestamp = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const content = `PEPTIDE RECONSTITUTION CALCULATION
Generated: ${timestamp}

=== INPUT VALUES ===
Desired Dose: ${currentDose} mg
Peptide Strength (Vial): ${currentStrength} mg
Bacteriostatic Water: ${currentWater} mL
Syringe Size: ${currentSyringeSize} mL (${totalSyringeUnits} units)

=== CALCULATION RESULTS ===
Concentration: ${concentration.toFixed(2)} mg/mL
Draw Amount: ${drawAmount} mL
Draw Amount (Units): ${drawUnits} units
Doses in Vial: ${dosesInVial}

=== RECONSTITUTION STEPS ===
1. Draw ${currentWater} mL of bacteriostatic water into a syringe
2. Inject into the vial containing ${currentStrength} mg peptide
3. Let the solution reconstitute for 5-10 minutes
4. Using your ${currentSyringeSize}mL syringe, draw ${drawAmount} mL (${drawUnits} units) for your ${currentDose} mg dose

=== IMPORTANT NOTES ===
- This calculator is for research purposes only
- All peptides are sold for research use only and are not intended for human consumption
- Always follow local laws and regulations
- Store reconstituted peptides in a cool, dark place (2-8°C refrigerator is ideal)
- Reconstituted peptides typically remain stable for 30 days when properly stored
- Always use sterile equipment and fresh needles

Generated by Red Helix Research Peptide Calculator
www.redhelixresearch.com`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `peptide-calculation-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateQRCodeURL = () => {
    const baseUrl = window.location.origin;
    const params = new URLSearchParams({
      dose: currentDose.toString(),
      strength: currentStrength.toString(),
      water: currentWater.toString(),
      syringeSize: currentSyringeSize.toString()
    });
    return `${baseUrl}${createPageUrl('PeptideInstructions')}?${params.toString()}`;
  };

  // Generate syringe markings based on size
  const getSyringeMarkings = () => {
    const size = currentSyringeSize;
    const totalUnits = size * 100;

    // Major markings configuration based on syringe size
    let majorInterval, minorInterval;
    if (size === 1) {
      majorInterval = 10;  // Every 10 units
      minorInterval = 5;   // Every 5 units
    } else if (size === 2) {
      majorInterval = 20;  // Every 20 units
      minorInterval = 10;  // Every 10 units
    } else {
      majorInterval = 50;  // Every 50 units for 3mL
      minorInterval = 10;  // Every 10 units
    }

    const majorMarkings = [];
    const minorMarkings = [];

    for (let i = 0; i <= totalUnits; i += majorInterval) {
      majorMarkings.push(i);
    }

    for (let i = 0; i <= totalUnits; i += minorInterval) {
      if (i % majorInterval !== 0) {
        minorMarkings.push(i);
      }
    }

    return { majorMarkings, minorMarkings, totalUnits };
  };

  const { majorMarkings, minorMarkings, totalUnits } = getSyringeMarkings();

  return (
    <div className="min-h-screen bg-white pt-24 lg:pt-32 pb-20">
      <SEO
        title="Peptide Dosage Calculator - Reconstitution Calculation Tool"
        description="Easy-to-use peptide reconstitution calculator for research. Calculate exact dosing, concentrations, and syringe measurements for peptide administration. Step-by-step reconstitution guide included."
        keywords="peptide calculator, reconstitution calculator, dosage calculator, peptide dosing, syringe calculator, concentration calculator, peptide mixing guide, reconstitution guide, peptide preparation"
      />

      {/* Header */}
      <div className="max-w-6xl mx-auto px-4 mb-8 md:mb-12">
        <Link to={createPageUrl('Home')}>
          <Button variant="ghost" className="mb-4 md:mb-6 hover:bg-slate-100 text-slate-600 font-bold uppercase tracking-widest text-xs">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-6 md:mb-8"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-[#dc2626]/5 border border-[#dc2626]/10 rounded-full mb-4 md:mb-6">
            <FlaskConical className="w-4 h-4 text-[#dc2626]" />
            <span className="text-[11px] font-black text-[#dc2626] uppercase tracking-widest">Precision Research Tool</span>
          </div>
          <h1 className="text-3xl md:text-5xl lg:text-7xl font-black text-slate-900 mb-3 uppercase tracking-tighter leading-none">
            PEPTIDE <span className="text-[#dc2626]">CALCULATOR</span>
          </h1>
          <p className="text-slate-500 text-base md:text-lg font-medium max-w-xl mx-auto">
            Calculate your research dosage with analytical precision
          </p>
        </motion.div>

        {/* Disclaimer */}
        <div className="bg-[#dc2626] rounded-2xl md:rounded-[32px] p-4 md:p-6 shadow-lg shadow-[#dc2626]/20">
          <p className="text-white text-xs md:text-sm text-center font-medium">
            <span className="font-black uppercase tracking-wider mr-2">Disclaimer:</span> This calculator is strictly for research purposes only. All peptides are sold for research use only and are not intended for human consumption.
          </p>
        </div>
      </div>

      {/* Main Calculator Grid */}
      <div className="max-w-6xl mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 md:gap-8">
          {/* LEFT SIDE - INPUTS */}
          <div className="space-y-4 md:space-y-6">
            {/* Syringe Size */}
            <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[32px] p-5 md:p-8 shadow-sm">
              <div className="flex items-center gap-2 mb-4">
                <Syringe className="w-5 h-5 text-[#dc2626]" />
                <label className="text-slate-900 font-black uppercase tracking-widest text-xs">Syringe Size</label>
                <Info className="w-4 h-4 text-slate-400" />
              </div>
              <Select value={syringeSize} onValueChange={setSyringeSize}>
                <SelectTrigger className="bg-white border-slate-200 text-slate-900 h-12 rounded-xl font-bold">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-white border-slate-200">
                  {syringeSizeOptions.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value} className="text-slate-900 font-bold">
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-slate-400 text-[11px] font-black uppercase tracking-wider mt-3 ml-1">
                Select the syringe size for administration
              </p>
            </div>

            {/* Dose */}
            <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[32px] p-5 md:p-8 shadow-sm">
              <div className="flex items-center gap-2 mb-4">
                <label className="text-slate-900 font-black uppercase tracking-widest text-xs">Dose (mg)</label>
                <Info className="w-4 h-4 text-slate-400" />
              </div>
              {dose !== 'other' ? (
                <>
                  <Select value={dose} onValueChange={setDose}>
                    <SelectTrigger className="bg-white border-slate-200 text-slate-900 h-12 rounded-xl font-bold mb-4">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-white border-slate-200">
                      {doseOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-slate-900 font-bold">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-slate-900 font-bold">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => setDose('other')}
                  >
                    Custom Value
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={doseCustom}
                    onChange={(e) => setDoseCustom(e.target.value)}
                    placeholder="Enter dose in mg"
                    className="w-full bg-white border border-slate-200 rounded-xl px-4 h-12 text-slate-900 placeholder-slate-300 focus:outline-none focus:border-[#dc2626] focus:ring-1 focus:ring-[#dc2626]/20 mb-4 font-bold transition-all"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => {
                      setDose('1');
                      setDoseCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Peptide Strength */}
            <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[32px] p-5 md:p-8 shadow-sm">
              <div className="flex items-center gap-2 mb-4">
                <label className="text-slate-900 font-black uppercase tracking-widest text-xs">Peptide Strength (mg)</label>
                <Info className="w-4 h-4 text-slate-400" />
              </div>
              {strength !== 'other' ? (
                <>
                  <Select value={strength} onValueChange={setStrength}>
                    <SelectTrigger className="bg-white border-slate-200 text-slate-900 h-12 rounded-xl font-bold mb-4">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-white border-slate-200">
                      {strengthOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-slate-900 font-bold">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-slate-900 font-bold">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => setStrength('other')}
                  >
                    Custom Value
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={strengthCustom}
                    onChange={(e) => setStrengthCustom(e.target.value)}
                    placeholder="Enter vial strength in mg"
                    className="w-full bg-white border border-slate-200 rounded-xl px-4 h-12 text-slate-900 placeholder-slate-300 focus:outline-none focus:border-[#dc2626] focus:ring-1 focus:ring-[#dc2626]/20 mb-4 font-bold transition-all"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => {
                      setStrength('10');
                      setStrengthCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Water Volume */}
            <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[32px] p-5 md:p-8 shadow-sm">
              <div className="flex items-center gap-2 mb-4">
                <label className="text-slate-900 font-black uppercase tracking-widest text-xs">Bacteriostatic Water (mL)</label>
                <Info className="w-4 h-4 text-slate-400" />
              </div>
              {water !== 'other' ? (
                <>
                  <Select value={water} onValueChange={setWater}>
                    <SelectTrigger className="bg-white border-slate-200 text-slate-900 h-12 rounded-xl font-bold mb-4">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-white border-slate-200">
                      {waterOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-slate-900 font-bold">
                          {opt} mL
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-slate-900 font-bold">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => setWater('other')}
                  >
                    Custom Value
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={waterCustom}
                    onChange={(e) => setWaterCustom(e.target.value)}
                    placeholder="Enter volume in mL"
                    className="w-full bg-white border border-slate-200 rounded-xl px-4 h-12 text-slate-900 placeholder-slate-300 focus:outline-none focus:border-[#dc2626] focus:ring-1 focus:ring-[#dc2626]/20 mb-4 font-bold transition-all"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-slate-200 text-slate-400 hover:text-[#dc2626] hover:border-[#dc2626]/30 w-full rounded-xl font-black uppercase tracking-widest text-[11px] h-10"
                    onClick={() => {
                      setWater('1.0');
                      setWaterCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>
          </div>

          {/* RIGHT SIDE - RESULTS */}
          <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[40px] p-5 md:p-10 sticky top-24 lg:top-32 h-fit shadow-sm">
            <h2 className="text-xl md:text-2xl font-black text-slate-900 mb-6 md:mb-8 uppercase tracking-tight">Reconstitution <span className="text-[#dc2626]">Results</span></h2>

            {!isValid ? (
              <div className="text-slate-400 text-center py-16 md:py-20 border-2 border-dashed border-slate-200 rounded-2xl md:rounded-[32px]">
                <Microscope className="w-10 h-10 text-slate-200 mx-auto mb-4" />
                <p className="font-black uppercase tracking-widest text-xs">Enter laboratory values to calculate</p>
              </div>
            ) : (
              <div className="space-y-4 md:space-y-6">
                {/* Results Cards */}
                <div className="grid gap-3 md:gap-4">
                  {/* Draw Amount */}
                  <div className="bg-white rounded-2xl md:rounded-3xl p-4 md:p-6 border border-slate-100 group hover:border-[#dc2626]/30 transition-all shadow-sm">
                    <p className="text-slate-400 text-[11px] font-black uppercase tracking-widest mb-2">Draw Volume</p>
                    <div className="flex items-baseline gap-2">
                      <p className="text-3xl md:text-4xl font-black text-slate-900">{drawAmount}</p>
                      <p className="text-[#dc2626] font-black text-lg md:text-xl uppercase tracking-widest">mL</p>
                    </div>
                  </div>

                  {/* Draw Units */}
                  <div className="bg-white rounded-2xl md:rounded-3xl p-4 md:p-6 border border-slate-100 group hover:border-[#dc2626]/30 transition-all shadow-sm">
                    <p className="text-slate-400 text-[11px] font-black uppercase tracking-widest mb-2">Syringe Units</p>
                    <div className="flex items-baseline gap-2">
                      <p className="text-3xl md:text-4xl font-black text-slate-900">{drawUnits}</p>
                      <p className="text-[#dc2626] font-black text-lg md:text-xl uppercase tracking-widest">Units</p>
                    </div>
                    <p className="text-slate-500 text-[11px] font-black uppercase tracking-widest mt-2">On {currentSyringeSize}mL Syringe</p>
                  </div>

                  <div className="grid grid-cols-2 gap-3 md:gap-4">
                    {/* Concentration */}
                    <div className="bg-white rounded-2xl md:rounded-3xl p-4 md:p-6 border border-slate-100 shadow-sm">
                      <p className="text-slate-400 text-[11px] font-black uppercase tracking-widest mb-2">Conc.</p>
                      <p className="text-lg md:text-xl font-black text-slate-900">{concentration.toFixed(2)} <span className="text-[#dc2626] text-xs">mg/mL</span></p>
                    </div>

                    {/* Doses in Vial */}
                    <div className="bg-white rounded-2xl md:rounded-3xl p-4 md:p-6 border border-slate-100 shadow-sm">
                      <p className="text-slate-400 text-[11px] font-black uppercase tracking-widest mb-2">Yield</p>
                      <p className="text-lg md:text-xl font-black text-slate-900">{dosesInVial} <span className="text-[#dc2626] text-xs">Doses</span></p>
                    </div>
                  </div>
                </div>

                {/* Warning Messages */}
                {parseFloat(drawAmount) > currentWater && (
                  <div className="bg-[#dc2626]/5 border border-[#dc2626]/20 rounded-2xl p-4 text-[#dc2626] text-xs font-bold text-center">
                    Draw volume exceeds available reconstituted solution.
                  </div>
                )}

                {exceedsSyringeCapacity && (
                  <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-amber-600 text-xs font-bold text-center">
                    Volume exceeds {currentSyringeSize}mL syringe capacity.
                  </div>
                )}

                {/* Action Buttons */}
                <div className="space-y-3 md:space-y-4 mt-6 md:mt-8 pt-6 md:pt-8 border-t border-slate-200">
                  <div className="flex gap-3 md:gap-4">
                    <Button
                      onClick={handleReset}
                      variant="outline"
                      className="flex-1 border-slate-200 text-slate-500 hover:text-[#dc2626] hover:border-[#dc2626]/30 rounded-2xl font-black uppercase tracking-widest text-[11px] h-12 md:h-14"
                    >
                      <RotateCcw className="w-4 h-4 mr-2" />
                      Reset
                    </Button>
                    <Button
                      onClick={handleDownload}
                      className="flex-1 bg-[#dc2626] hover:bg-[#b91c1c] text-white rounded-2xl font-black uppercase tracking-widest text-[11px] h-12 md:h-14 shadow-lg shadow-[#dc2626]/20"
                    >
                      Export Data
                    </Button>
                  </div>
                  <Button
                    onClick={() => setShowQRCode(true)}
                    variant="outline"
                    className="w-full border-slate-200 text-slate-500 hover:text-[#dc2626] hover:border-[#dc2626]/30 rounded-2xl font-black uppercase tracking-widest text-[11px] h-12 md:h-14"
                  >
                      <QrCode className="w-4 h-4 mr-2" />
                      Generate QR Code for Phone
                  </Button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Syringe Visualization */}
      {isValid && (
        <div className="max-w-6xl mx-auto px-4 mt-8 md:mt-12">
          <div className="bg-white rounded-2xl md:rounded-[32px] p-5 md:p-8 border border-slate-100 shadow-sm overflow-x-auto">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 gap-3">
              <p className="text-slate-900 text-base md:text-lg font-black uppercase tracking-tight">
                Syringe Markings ({currentSyringeSize}mL / {totalUnits} units)
              </p>
              <div className="flex items-center gap-2 text-xs md:text-sm text-slate-500 font-bold bg-slate-50 px-4 py-2 rounded-full border border-slate-100">
                <Syringe className="w-4 h-4 text-[#dc2626]" />
                <span>{currentSyringeSize}mL syringe selected</span>
              </div>
            </div>
            <svg viewBox="0 0 1100 120" className="w-full h-32 md:h-40" style={{ minWidth: '700px' }}>
              {/* Syringe barrel */}
              <rect x="50" y="30" width="1000" height="60" rx="8" fill="none" stroke="#e2e8f0" strokeWidth="3" />

              {/* Fluid fill animation */}
              <defs>
                <linearGradient id="fluidGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" stopColor="rgba(220, 38, 38, 0.8)" />
                  <stop offset="50%" stopColor="rgba(239, 68, 68, 0.9)" />
                  <stop offset="100%" stopColor="rgba(220, 38, 38, 0.8)" />
                </linearGradient>
                <filter id="fluidShadow" x="-50%" y="-50%" width="200%" height="200%">
                  <feGaussianBlur in="SourceGraphic" stdDeviation="1" />
                </filter>
              </defs>

              {/* Fluid fill with wave effect */}
              <motion.g>
                {/* Main fluid body */}
                <motion.rect
                  x="50"
                  y="30"
                  width={Math.min(1000, (parseFloat(drawUnits) / totalUnits) * 1000)}
                  height="60"
                  rx="4"
                  fill="url(#fluidGradient)"
                  initial={{ width: 0, opacity: 0 }}
                  animate={{ width: Math.min(1000, (parseFloat(drawUnits) / totalUnits) * 1000), opacity: 1 }}
                  transition={{ type: 'spring', stiffness: 80, damping: 20, duration: 1.2 }}
                />

                {/* Shimmer effect */}
                <motion.ellipse
                  cx={50 + (parseFloat(drawUnits) / totalUnits) * 500}
                  cy="40"
                  rx="80"
                  ry="15"
                  fill="rgba(255, 255, 255, 0.2)"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: [0, 0.6, 0] }}
                  transition={{ delay: 0.6, duration: 0.8 }}
                />
              </motion.g>

              {/* Major markings */}
              {majorMarkings.map((units) => (
                <g key={units}>
                  <line
                    x1={50 + (units / totalUnits) * 1000}
                    y1="10"
                    x2={50 + (units / totalUnits) * 1000}
                    y2="25"
                    stroke="#64748b"
                    strokeWidth="2"
                  />
                  <text
                    x={50 + (units / totalUnits) * 1000}
                    y="8"
                    textAnchor="middle"
                    fontSize={currentSyringeSize === 3 ? "14" : "16"}
                    fontWeight="700"
                    fill="#475569"
                  >
                    {units}
                  </text>
                </g>
              ))}

              {/* Minor markings */}
              {minorMarkings.map((units) => (
                <line
                  key={`minor-${units}`}
                  x1={50 + (units / totalUnits) * 1000}
                  y1="15"
                  x2={50 + (units / totalUnits) * 1000}
                  y2="25"
                  stroke="#94a3b8"
                  strokeWidth="1.5"
                />
              ))}

              {/* Current draw indicator */}
              {parseFloat(drawUnits) <= totalUnits && (
                <line
                  x1={50 + (parseFloat(drawUnits) / totalUnits) * 1000}
                  y1="30"
                  x2={50 + (parseFloat(drawUnits) / totalUnits) * 1000}
                  y2="90"
                  stroke="#dc2626"
                  strokeWidth="3"
                  strokeDasharray="5,5"
                />
              )}
            </svg>
            <p className="text-center text-slate-900 font-bold text-sm md:text-lg mt-6 md:mt-8 bg-slate-50 py-3 md:py-4 rounded-xl border border-slate-100">
              Draw to <span className="text-xl md:text-2xl text-[#dc2626] font-black">{drawUnits}</span> units ({drawAmount} mL) on your {currentSyringeSize}mL syringe
            </p>
          </div>

          {/* Reconstitution Steps */}
          <div className="bg-slate-50 rounded-2xl md:rounded-[32px] p-5 md:p-8 border border-slate-100 mt-4 md:mt-6 shadow-sm">
            <p className="text-slate-900 text-base md:text-lg font-black uppercase tracking-tight mb-4 flex items-center gap-2">
              <RotateCcw className="w-5 h-5 text-[#dc2626]" />
              Reconstitution Steps
            </p>
            <ol className="space-y-3 md:space-y-4 text-sm text-slate-600 list-decimal list-inside font-medium">
              <li className="pl-2">Draw <span className="text-slate-900 font-bold">{currentWater} mL</span> of bacteriostatic water into a syringe</li>
              <li className="pl-2">Inject into the vial containing <span className="text-slate-900 font-bold">{currentStrength} mg</span> peptide</li>
              <li className="pl-2">Let the solution reconstitute for 5-10 minutes</li>
              <li className="pl-2">Using your <span className="text-[#dc2626] font-bold">{currentSyringeSize}mL syringe</span>, draw <span className="text-slate-900 font-bold">{drawAmount} mL ({drawUnits} units)</span> for your {currentDose} mg dose – <Link to={createPageUrl('PeptideReconstitutionGuide')} className="text-[#dc2626] hover:text-[#b91c1c] underline font-bold">Full Guide Here</Link></li>
            </ol>
          </div>
        </div>
      )}

      {/* How to Use Section */}
      <div className="max-w-6xl mx-auto px-4 mt-10 md:mt-16">
        <div className="bg-slate-50 border border-slate-100 rounded-2xl md:rounded-[32px] p-6 md:p-10 shadow-sm">
          <h3 className="text-xl md:text-2xl font-black text-slate-900 mb-6 md:mb-8 uppercase tracking-tight flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#dc2626] flex items-center justify-center shadow-lg shadow-[#dc2626]/20">
              <Info className="w-4 h-4 text-white" />
            </div>
            How to Use
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6 md:gap-8">
            <div className="space-y-2">
              <p className="font-black text-slate-900 uppercase tracking-wider text-xs flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-[#dc2626]/10 text-[#dc2626] flex items-center justify-center text-[11px] font-black">1</span>
                Select syringe size
              </p>
              <p className="text-slate-500 text-sm font-medium pl-8">Choose the syringe you'll use (1mL, 2mL, or 3mL).</p>
            </div>
            <div className="space-y-2">
              <p className="font-black text-slate-900 uppercase tracking-wider text-xs flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-[#dc2626]/10 text-[#dc2626] flex items-center justify-center text-[11px] font-black">2</span>
                Set your dose
              </p>
              <p className="text-slate-500 text-sm font-medium pl-8">The amount of peptide you want to administer in milligrams.</p>
            </div>
            <div className="space-y-2">
              <p className="font-black text-slate-900 uppercase tracking-wider text-xs flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-[#dc2626]/10 text-[#dc2626] flex items-center justify-center text-[11px] font-black">3</span>
                Enter peptide strength
              </p>
              <p className="text-slate-500 text-sm font-medium pl-8">Total milligrams in your vial from the manufacturer.</p>
            </div>
            <div className="space-y-2">
              <p className="font-black text-slate-900 uppercase tracking-wider text-xs flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-[#dc2626]/10 text-[#dc2626] flex items-center justify-center text-[11px] font-black">4</span>
                Choose water volume
              </p>
              <p className="text-slate-500 text-sm font-medium pl-8">The mL of bacteriostatic water you're using for reconstitution.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Legal Disclaimer - matches Products.jsx */}
      <div className="max-w-6xl mx-auto px-4 mt-6 md:mt-10">
        <div className="p-5 md:p-8 bg-slate-50 rounded-2xl md:rounded-[32px] border border-slate-100 text-center">
          <p className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] mb-3">Research Use Only</p>
          <p className="text-xs text-slate-500 max-w-4xl mx-auto leading-relaxed font-medium">
            This calculator and all products listed are strictly for LABORATORY AND SCIENTIFIC RESEARCH PURPOSES ONLY.
            Not for human consumption, veterinary use, or any form of clinical application.
          </p>
        </div>
      </div>

      {/* QR Code Modal */}
      <Dialog open={showQRCode} onOpenChange={setShowQRCode}>
        <DialogContent className="bg-white border-slate-100 max-w-md rounded-2xl md:rounded-[32px] p-0 overflow-hidden">
          <div className="text-center p-6 md:p-8">
            <h2 className="text-xl md:text-2xl font-black text-slate-900 mb-2 uppercase tracking-tight">
              Scan with Your Phone
            </h2>
            <p className="text-slate-500 text-sm mb-6 md:mb-8 font-medium">
              This QR code will take you to a mobile-friendly instruction page with your calculations
            </p>

            {/* QR Code */}
            <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm inline-block mb-6 md:mb-8">
              <QRCodeSVG
                value={generateQRCodeURL()}
                size={200}
                level="H"
                includeMargin={true}
              />
            </div>

            {/* Instructions */}
            <div className="bg-slate-50 border border-slate-100 rounded-2xl p-5 md:p-6 text-left mb-6">
              <p className="text-slate-900 text-xs font-black uppercase tracking-wider mb-3 flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-[#dc2626] text-white flex items-center justify-center text-[9px] font-black">i</span>
                How to use
              </p>
              <ol className="text-slate-600 text-sm space-y-2 list-decimal list-inside font-medium">
                <li>Open your phone's camera</li>
                <li>Point it at the QR code</li>
                <li>Tap the notification to open the link</li>
                <li>Follow the step-by-step instructions</li>
              </ol>
            </div>

            <Button
              onClick={() => setShowQRCode(false)}
              className="w-full bg-[#dc2626] hover:bg-[#b91c1c] text-white font-black h-12 rounded-xl uppercase tracking-widest text-xs shadow-lg shadow-[#dc2626]/20"
            >
              Close Window
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
