import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Info, RotateCcw, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { motion } from 'framer-motion';

export default function PeptideCalculator() {
  const [dose, setDose] = useState('1');
  const [doseCustom, setDoseCustom] = useState('');
  const [strength, setStrength] = useState('10');
  const [strengthCustom, setStrengthCustom] = useState('');
  const [water, setWater] = useState('1.0');
  const [waterCustom, setWaterCustom] = useState('');

  // Fetch products
  const { data: products = [] } = useQuery({
    queryKey: ['products'],
    queryFn: () => base44.entities.Product.list(),
  });

  const doseOptions = ['0.1', '0.25', '0.5', '1', '2.5', '5', '7.5', '10', '12.5', '15', '50'];
  const strengthOptions = ['1', '5', '10', '15', '20', '30', '50', '1000'];
  const waterOptions = ['1.0', '2.0', '3.0'];

  const currentDose = dose === 'other' ? parseFloat(doseCustom) || 0 : parseFloat(dose);
  const currentStrength = strength === 'other' ? parseFloat(strengthCustom) || 0 : parseFloat(strength);
  const currentWater = water === 'other' ? parseFloat(waterCustom) || 0 : parseFloat(water);

  const concentration = currentWater > 0 ? currentStrength / currentWater : 0;
  const drawAmount = concentration > 0 ? (currentDose / concentration).toFixed(2) : 0;
  const drawUnits = concentration > 0 ? (currentDose / concentration * 100).toFixed(0) : 0;
  const dosesInVial = concentration > 0 && currentDose > 0 ? Math.floor(currentStrength / currentDose) : 0;

  const isValid = currentDose > 0 && currentStrength > 0 && currentWater > 0;

  const handleReset = () => {
    setDose('1');
    setDoseCustom('');
    setStrength('10');
    setStrengthCustom('');
    setWater('1.0');
    setWaterCustom('');
  };

  const handleDownload = () => {
    const timestamp = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
    
    const content = `PEPTIDE RECONSTITUTION CALCULATION
Generated: ${timestamp}

=== INPUT VALUES ===
Desired Dose: ${currentDose} mg
Peptide Strength (Vial): ${currentStrength} mg
Bacteriostatic Water: ${currentWater} mL

=== CALCULATION RESULTS ===
Concentration: ${concentration.toFixed(2)} mg/mL
Draw Amount: ${drawAmount} mL
Draw Amount (Units): ${drawUnits} units
Doses in Vial: ${dosesInVial}

=== RECONSTITUTION STEPS ===
1. Draw ${currentWater} mL of bacteriostatic water into a syringe
2. Inject into the vial containing ${currentStrength} mg peptide
3. Let the solution reconstitute for 5-10 minutes
4. For your ${currentDose} mg dose, draw ${drawAmount} mL (${drawUnits} units)

=== IMPORTANT NOTES ===
- This calculator is for research purposes only
- All peptides are sold for research use only and are not intended for human consumption
- Always follow local laws and regulations
- Store reconstituted peptides in a cool, dark place (2-8°C refrigerator is ideal)
- Reconstituted peptides typically remain stable for 30 days when properly stored
- Always use sterile equipment and fresh needles

Generated by Red Dirt Research Peptide Calculator
www.reddirtresearch.com`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `peptide-calculation-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-stone-950 pt-32 pb-20">
      {/* Header */}
            <div className="max-w-6xl mx-auto px-4 mb-12">
              <div className="text-center mb-8">
                <h1 className="text-5xl font-black text-amber-50 mb-3">Peptide Reconstitution Calculator</h1>
                <p className="text-stone-400 text-lg">Calculate your peptide dosage with precision</p>
              </div>

              {/* Disclaimer */}
              <div className="bg-yellow-950/30 border border-yellow-700/50 rounded-lg p-4 mb-8">
                <p className="text-yellow-100 text-sm text-center">
                  <span className="font-semibold">⚠️ Disclaimer:</span> This calculator is strictly for research purposes only. All peptides are sold for research use only and are not intended for human consumption. Always follow local laws and regulations.
                </p>
              </div>
            </div>

      {/* Main Calculator Grid */}
      <div className="max-w-6xl mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* LEFT SIDE - INPUTS */}
          <div className="space-y-6">
            {/* Dose */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Dose</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {dose !== 'other' ? (
                <>
                  <Select value={dose} onValueChange={setDose}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {doseOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setDose('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={doseCustom}
                    onChange={(e) => setDoseCustom(e.target.value)}
                    placeholder="Enter dose"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setDose('1');
                      setDoseCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Peptide Strength */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Peptide Strength (Vial)</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {strength !== 'other' ? (
                <>
                  <Select value={strength} onValueChange={setStrength}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {strengthOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setStrength('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={strengthCustom}
                    onChange={(e) => setStrengthCustom(e.target.value)}
                    placeholder="Enter strength"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setStrength('10');
                      setStrengthCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Water Volume */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Bacteriostatic Water</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {water !== 'other' ? (
                <>
                  <Select value={water} onValueChange={setWater}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {waterOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mL
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setWater('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={waterCustom}
                    onChange={(e) => setWaterCustom(e.target.value)}
                    placeholder="Enter volume"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setWater('1.0');
                      setWaterCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}

              {/* Vial Visualization */}
              <div className="mt-6 flex justify-center">
                <div className="relative w-48 h-64">
                  <svg viewBox="0 0 200 300" className="w-full h-full">
                    <defs>
                      <linearGradient id="vialFluidGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                        <stop offset="0%" stopColor="rgba(59, 130, 246, 0.6)" />
                        <stop offset="50%" stopColor="rgba(96, 165, 250, 0.5)" />
                        <stop offset="100%" stopColor="rgba(59, 130, 246, 0.7)" />
                      </linearGradient>
                      <clipPath id="vialClip">
                        <rect x="52" y="62" width="96" height="196" rx="6" />
                      </clipPath>
                    </defs>

                    {/* Vial cap */}
                    <ellipse cx="100" cy="30" rx="35" ry="8" fill="#666" />
                    <rect x="65" y="30" width="70" height="15" fill="#666" />
                    
                    {/* Vial neck */}
                    <path d="M 75 45 L 80 60 L 120 60 L 125 45 Z" fill="#e5e5e5" stroke="#999" strokeWidth="1" />
                    
                    {/* Main vial body - interior from y=62 to y=258 (196px total) */}
                    <rect x="50" y="60" width="100" height="200" rx="8" fill="rgba(255, 255, 255, 0.15)" stroke="#999" strokeWidth="2" />
                    
                    {/* Barn logo on vial */}
                    <image 
                      href="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6972f2b59e2787f045b7ae0d/af30dbf80_download.png"
                      x="75" 
                      y="140" 
                      width="50" 
                      height="50"
                      opacity="0.4"
                    />
                    
                    {/* Water fill - precisely calculated
                        Vial interior: 196px from y=62 (top) to y=258 (bottom)
                        1ml = 196/3 = 65.33px height, top at y=192.67
                        2ml = 392/3 = 130.67px height, top at y=127.33
                        3ml = 196px height, top at y=62
                    */}
                    <g clipPath="url(#vialClip)">
                      <motion.rect
                        x="52"
                        y={(() => {
                          const vialTop = 62;
                          const vialHeight = 196;
                          const fillRatio = Math.min(currentWater, 3) / 3;
                          const waterHeight = fillRatio * vialHeight;
                          return vialTop + (vialHeight - waterHeight);
                        })()}
                        width="96"
                        height={(() => {
                          const vialHeight = 196;
                          const fillRatio = Math.min(currentWater, 3) / 3;
                          return fillRatio * vialHeight;
                        })()}
                        fill="url(#vialFluidGradient)"
                        initial={{ height: 0 }}
                        animate={{ 
                          height: (() => {
                            const vialHeight = 196;
                            const fillRatio = Math.min(currentWater, 3) / 3;
                            return fillRatio * vialHeight;
                          })(),
                          y: (() => {
                            const vialTop = 62;
                            const vialHeight = 196;
                            const fillRatio = Math.min(currentWater, 3) / 3;
                            const waterHeight = fillRatio * vialHeight;
                            return vialTop + (vialHeight - waterHeight);
                          })()
                        }}
                        transition={{ type: 'spring', stiffness: 100, damping: 15 }}
                      />
                    </g>
                    
                    {/* Vial bottom cap */}
                    <ellipse cx="100" cy="260" rx="50" ry="8" fill="#e5e5e5" stroke="#999" strokeWidth="1" />
                    
                    {/* Volume markings - precisely positioned to match water levels
                        1ml line: vialTop + (2/3 * vialHeight) = 62 + 130.67 = 192.67
                        2ml line: vialTop + (1/3 * vialHeight) = 62 + 65.33 = 127.33
                        3ml line: vialTop = 62
                    */}
                    <line x1="150" y1="192.67" x2="165" y2="192.67" stroke="#999" strokeWidth="1.5" />
                    <text x="170" y="197" fontSize="12" fill="#999">1ml</text>
                    
                    <line x1="150" y1="127.33" x2="165" y2="127.33" stroke="#999" strokeWidth="1.5" />
                    <text x="170" y="132" fontSize="12" fill="#999">2ml</text>
                    
                    <line x1="150" y1="62" x2="165" y2="62" stroke="#999" strokeWidth="1.5" />
                    <text x="170" y="67" fontSize="12" fill="#999">3ml</text>
                  </svg>
                  
                  {/* Current volume label */}
                  <div className="absolute bottom-0 left-0 right-0 text-center">
                    <p className="text-blue-400 font-bold text-sm">{currentWater} mL</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* RIGHT SIDE - RESULTS */}
          <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-8 sticky top-32 h-fit">
            <h2 className="text-2xl font-bold text-amber-50 mb-8">Results</h2>

            {!isValid ? (
              <div className="text-stone-400 text-center py-12">
                <p>Enter values to calculate</p>
              </div>
            ) : (
              <div className="space-y-6">
                {/* Results Cards */}
                <div className="space-y-5">
                {/* Draw Amount */}
                <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                  <p className="text-stone-400 text-sm mb-2">Draw to</p>
                  <p className="text-3xl font-bold text-red-600">{drawAmount} mL</p>
                </div>

                {/* Draw Units */}
                <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                  <p className="text-stone-400 text-sm mb-2">Or draw to</p>
                  <p className="text-3xl font-bold text-red-600">{drawUnits} units</p>
                </div>

                {/* Concentration */}
                <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                  <p className="text-stone-400 text-sm mb-2">Concentration</p>
                  <p className="text-3xl font-bold text-red-600">{concentration.toFixed(2)}</p>
                  <p className="text-stone-500 text-sm mt-1">mg/mL</p>
                </div>

                {/* Doses in Vial */}
                <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                  <p className="text-stone-400 text-sm mb-2">Doses in vial</p>
                  <p className="text-3xl font-bold text-red-600">{dosesInVial}</p>
                </div>

                {drawAmount > currentWater && (
                  <div className="bg-red-600/20 border border-red-600/50 rounded-lg p-4 text-red-400 text-sm mt-6">
                    ⚠️ Draw amount exceeds available volume. Adjust dose or water.
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex gap-3 mt-8 pt-6 border-t border-stone-700">
                  <Button
                    onClick={handleReset}
                    variant="outline"
                    className="flex-1 border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600"
                  >
                    <RotateCcw className="w-4 h-4 mr-2" />
                    Reset
                  </Button>
                  <Button 
                    onClick={handleDownload}
                    className="flex-1 bg-red-600 hover:bg-red-700 text-amber-50"
                  >
                    Download Results
                  </Button>
                </div>
                </div>
                </div>
                )}
                </div>
                </div>
                </div>

                {/* Syringe Visualization */}
                {isValid && (
                <div className="max-w-6xl mx-auto px-4 mt-12">
                  <div className="bg-stone-800/50 rounded-lg p-6 border border-stone-700 overflow-x-auto">
                    <p className="text-stone-400 text-sm mb-4 font-semibold">Syringe Markings (1mL)</p>
                    <svg viewBox="0 0 1100 120" className="w-full h-40" style={{ minWidth: '900px' }}>
                      {/* Syringe barrel */}
                      <rect x="50" y="30" width="1000" height="60" rx="8" fill="none" stroke="currentColor" strokeWidth="3" className="text-red-600" />

                      {/* Fluid fill animation */}
                      <defs>
                        <linearGradient id="fluidGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                          <stop offset="0%" stopColor="rgba(220, 38, 38, 0.5)" />
                          <stop offset="50%" stopColor="rgba(239, 68, 68, 0.6)" />
                          <stop offset="100%" stopColor="rgba(220, 38, 38, 0.7)" />
                        </linearGradient>
                        <filter id="fluidShadow" x="-50%" y="-50%" width="200%" height="200%">
                          <feGaussianBlur in="SourceGraphic" stdDeviation="1" />
                        </filter>
                      </defs>

                      {/* Fluid fill with wave effect */}
                      <motion.g>
                        {/* Main fluid body */}
                        <motion.rect
                          x="50"
                          y="30"
                          width={Math.min(1000, (drawUnits / 100) * 1000)}
                          height="60"
                          rx="4"
                          fill="url(#fluidGradient)"
                          initial={{ width: 0, opacity: 0 }}
                          animate={{ width: Math.min(1000, (drawUnits / 100) * 1000), opacity: 1 }}
                          transition={{ type: 'spring', stiffness: 80, damping: 20, duration: 1.2 }}
                        />
                        
                        {/* Wave splash effect at top */}
                        <motion.path
                          d={`M 50 35 Q ${55 + (drawUnits / 100) * 1000 * 0.25} 20, ${100 + (drawUnits / 100) * 1000 * 0.5} 32 T ${Math.min(1050, 50 + (drawUnits / 100) * 1000)} 35`}
                          fill="none"
                          stroke="rgba(239, 68, 68, 0.8)"
                          strokeWidth="2"
                          strokeLinecap="round"
                          initial={{ opacity: 0, pathLength: 0 }}
                          animate={{ opacity: 0, pathLength: 1 }}
                          transition={{ delay: 0.4, duration: 0.6 }}
                          filter="url(#fluidShadow)"
                        />

                        {/* Shimmer effect */}
                        <motion.ellipse
                          cx={50 + (drawUnits / 100) * 500}
                          cy="40"
                          rx="80"
                          ry="15"
                          fill="rgba(255, 255, 255, 0.15)"
                          initial={{ opacity: 0 }}
                          animate={{ opacity: [0, 0.6, 0] }}
                          transition={{ delay: 0.6, duration: 0.8 }}
                        />
                      </motion.g>

                      {/* Major markings (every 10 units) */}
                      {Array.from({ length: 11 }, (_, i) => i * 10).map((units) => (
                        <g key={units}>
                          <line
                            x1={50 + (units / 100) * 1000}
                            y1="10"
                            x2={50 + (units / 100) * 1000}
                            y2="25"
                            stroke="currentColor"
                            strokeWidth="2"
                            className="text-red-600"
                          />
                          <text
                            x={50 + (units / 100) * 1000}
                            y="8"
                            textAnchor="middle"
                            fontSize="16"
                            fontWeight="700"
                            fill="currentColor"
                            className="text-red-600"
                          >
                            {units}
                          </text>
                        </g>
                      ))}

                      {/* Minor markings (every 5 units) */}
                      {Array.from({ length: 20 }, (_, i) => (i * 5)).filter(u => u % 10 !== 0).map((units) => (
                        <line
                          key={`minor-${units}`}
                          x1={50 + (units / 100) * 1000}
                          y1="15"
                          x2={50 + (units / 100) * 1000}
                          y2="25"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          className="text-red-600"
                        />
                      ))}

                      {/* Current draw indicator */}
                      <line
                        x1={50 + (drawUnits / 100) * 1000}
                        y1="30"
                        x2={50 + (drawUnits / 100) * 1000}
                        y2="90"
                        stroke="currentColor"
                        strokeWidth="3"
                        className="text-amber-400"
                        strokeDasharray="5,5"
                      />
                    </svg>
                    <p className="text-center text-red-600 font-bold text-lg mt-4">Draw to <span className="text-2xl">{drawUnits}</span> units ({drawAmount} mL)</p>
                  </div>

                  {/* Reconstitution Steps */}
                  <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700 mt-6">
                    <p className="text-stone-400 text-sm font-semibold mb-3">Reconstitution Steps:</p>
                    <ol className="space-y-2 text-sm text-stone-300 list-decimal list-inside">
                      <li>Draw {currentWater} mL of bacteriostatic water into a syringe</li>
                      <li>Inject into the vial containing {currentStrength} mg peptide</li>
                      <li>Let the solution reconstitute for 5-10 minutes</li>
                      <li>For your {currentDose} mg dose, draw {drawAmount} mL ({drawUnits} units) – <Link to={createPageUrl('PeptideReconstitutionGuide')} className="text-red-600 hover:text-red-500 underline">Full Guide Here</Link></li>
                    </ol>
                  </div>
                </div>
                )}

                {/* Footer Info */}
      <div className="max-w-6xl mx-auto px-4 mt-16">
        <div className="bg-stone-900/30 border border-stone-700 rounded-lg p-8">
          <h3 className="text-xl font-bold text-amber-50 mb-4">How to use</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-stone-400 text-sm">
            <div>
              <p className="font-semibold text-amber-50 mb-2">1. Set your dose</p>
              <p>The amount of peptide you want to administer in milligrams.</p>
            </div>
            <div>
              <p className="font-semibold text-amber-50 mb-2">2. Enter peptide strength</p>
              <p>Total milligrams in your vial from the manufacturer.</p>
            </div>
            <div>
              <p className="font-semibold text-amber-50 mb-2">3. Choose water volume</p>
              <p>The mL of bacteriostatic water you're using for reconstitution.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}