import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Info, RotateCcw, ExternalLink, Syringe, QrCode } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { motion } from 'framer-motion';
import SEO from '@/components/SEO';
import { QRCodeSVG } from 'qrcode.react';
import { Dialog, DialogContent } from '@/components/ui/dialog';

export default function PeptideCalculator() {
  const [dose, setDose] = useState('1');
  const [doseCustom, setDoseCustom] = useState('');
  const [strength, setStrength] = useState('10');
  const [strengthCustom, setStrengthCustom] = useState('');
  const [water, setWater] = useState('1.0');
  const [waterCustom, setWaterCustom] = useState('');
  const [syringeSize, setSyringeSize] = useState('1'); // '1', '2', or '3' mL
  const [showQRCode, setShowQRCode] = useState(false);

  // Fetch products
  const { data: products = [] } = useQuery({
    queryKey: ['products'],
    queryFn: () => base44.entities.Product.list(),
  });

  const doseOptions = ['0.1', '0.25', '0.5', '1', '2.5', '5', '7.5', '10', '12.5', '15', '50'];
  const strengthOptions = ['1', '5', '10', '15', '20', '30', '50', '1000'];
  const waterOptions = ['1.0', '2.0', '3.0'];
  const syringeSizeOptions = [
    { value: '1', label: '1 mL Syringe (100 units)', units: 100 },
    { value: '2', label: '2 mL Syringe (200 units)', units: 200 },
    { value: '3', label: '3 mL Syringe (300 units)', units: 300 }
  ];

  const currentDose = dose === 'other' ? parseFloat(doseCustom) || 0 : parseFloat(dose);
  const currentStrength = strength === 'other' ? parseFloat(strengthCustom) || 0 : parseFloat(strength);
  const currentWater = water === 'other' ? parseFloat(waterCustom) || 0 : parseFloat(water);
  const currentSyringeSize = parseFloat(syringeSize);
  const totalSyringeUnits = currentSyringeSize * 100; // 100 units per mL

  const concentration = currentWater > 0 ? currentStrength / currentWater : 0;
  const drawAmountML = concentration > 0 ? (currentDose / concentration) : 0;
  const drawAmount = drawAmountML.toFixed(3);
  // Units are always 100 per mL regardless of syringe size
  const drawUnits = concentration > 0 ? (drawAmountML * 100).toFixed(0) : 0;
  const dosesInVial = concentration > 0 && currentDose > 0 ? Math.floor(currentStrength / currentDose) : 0;

  const isValid = currentDose > 0 && currentStrength > 0 && currentWater > 0;
  
  // Check if draw exceeds syringe capacity
  const exceedsSyringeCapacity = drawAmountML > currentSyringeSize;

  const handleReset = () => {
    setDose('1');
    setDoseCustom('');
    setStrength('10');
    setStrengthCustom('');
    setWater('1.0');
    setWaterCustom('');
    setSyringeSize('1');
  };

  const handleDownload = () => {
    const timestamp = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
    
    const content = `PEPTIDE RECONSTITUTION CALCULATION
Generated: ${timestamp}

=== INPUT VALUES ===
Desired Dose: ${currentDose} mg
Peptide Strength (Vial): ${currentStrength} mg
Bacteriostatic Water: ${currentWater} mL
Syringe Size: ${currentSyringeSize} mL (${totalSyringeUnits} units)

=== CALCULATION RESULTS ===
Concentration: ${concentration.toFixed(2)} mg/mL
Draw Amount: ${drawAmount} mL
Draw Amount (Units): ${drawUnits} units
Doses in Vial: ${dosesInVial}

=== RECONSTITUTION STEPS ===
1. Draw ${currentWater} mL of bacteriostatic water into a syringe
2. Inject into the vial containing ${currentStrength} mg peptide
3. Let the solution reconstitute for 5-10 minutes
4. Using your ${currentSyringeSize}mL syringe, draw ${drawAmount} mL (${drawUnits} units) for your ${currentDose} mg dose

=== IMPORTANT NOTES ===
- This calculator is for research purposes only
- All peptides are sold for research use only and are not intended for human consumption
- Always follow local laws and regulations
- Store reconstituted peptides in a cool, dark place (2-8°C refrigerator is ideal)
- Reconstituted peptides typically remain stable for 30 days when properly stored
- Always use sterile equipment and fresh needles

Generated by Red Helix Research Peptide Calculator
www.redhelixresearch.com`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `peptide-calculation-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateQRCodeURL = () => {
    const params = new URLSearchParams({
      dose: currentDose.toString(),
      strength: currentStrength.toString(),
      water: currentWater.toString(),
      syringeSize: currentSyringeSize.toString()
    });
    // Use full production URL with proper Base44 page routing
    const pagePath = createPageUrl('PeptideInstructions').replace(/^\//, '');
    return `https://www.redhelixresearch.com/${pagePath}?${params.toString()}`;
  };

  // Generate syringe markings based on size
  const getSyringeMarkings = () => {
    const size = currentSyringeSize;
    const totalUnits = size * 100;
    
    // Major markings configuration based on syringe size
    let majorInterval, minorInterval;
    if (size === 1) {
      majorInterval = 10;  // Every 10 units
      minorInterval = 5;   // Every 5 units
    } else if (size === 2) {
      majorInterval = 20;  // Every 20 units
      minorInterval = 10;  // Every 10 units
    } else {
      majorInterval = 50;  // Every 50 units for 3mL
      minorInterval = 10;  // Every 10 units
    }
    
    const majorMarkings = [];
    const minorMarkings = [];
    
    for (let i = 0; i <= totalUnits; i += majorInterval) {
      majorMarkings.push(i);
    }
    
    for (let i = 0; i <= totalUnits; i += minorInterval) {
      if (i % majorInterval !== 0) {
        minorMarkings.push(i);
      }
    }
    
    return { majorMarkings, minorMarkings, totalUnits };
  };

  const { majorMarkings, minorMarkings, totalUnits } = getSyringeMarkings();

  return (
    <div className="min-h-screen bg-stone-950 pt-32 pb-20">
      <SEO 
        title="Peptide Dosage Calculator - Reconstitution Calculation Tool"
        description="Easy-to-use peptide reconstitution calculator for research. Calculate exact dosing, concentrations, and syringe measurements for peptide administration. Step-by-step reconstitution guide included."
        keywords="peptide calculator, reconstitution calculator, dosage calculator, peptide dosing, syringe calculator, concentration calculator, peptide mixing guide, reconstitution guide, peptide preparation"
      />
      {/* Header */}
      <div className="max-w-6xl mx-auto px-4 mb-12">
        <div className="text-center mb-8">
          <h1 className="text-5xl font-black text-amber-50 mb-3">Peptide Reconstitution Calculator</h1>
          <p className="text-stone-400 text-lg">Calculate your peptide dosage with precision</p>
        </div>

        {/* Disclaimer */}
        <div className="bg-yellow-950/30 border border-yellow-700/50 rounded-lg p-4 mb-8">
          <p className="text-yellow-100 text-sm text-center">
            <span className="font-semibold">⚠️ Disclaimer:</span> This calculator is strictly for research purposes only. All peptides are sold for research use only and are not intended for human consumption. Always follow local laws and regulations.
          </p>
        </div>
      </div>

      {/* Main Calculator Grid */}
      <div className="max-w-6xl mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* LEFT SIDE - INPUTS */}
          <div className="space-y-6">
            {/* Syringe Size - NEW */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <Syringe className="w-5 h-5 text-red-600" />
                <label className="text-amber-50 font-semibold">Syringe Size</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              <Select value={syringeSize} onValueChange={setSyringeSize}>
                <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-stone-800 border-stone-600">
                  {syringeSizeOptions.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value} className="text-amber-50">
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-stone-500 text-xs mt-2">
                Select the syringe size you'll use for administration
              </p>
            </div>

            {/* Dose */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Dose</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {dose !== 'other' ? (
                <>
                  <Select value={dose} onValueChange={setDose}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {doseOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setDose('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={doseCustom}
                    onChange={(e) => setDoseCustom(e.target.value)}
                    placeholder="Enter dose"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setDose('1');
                      setDoseCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Peptide Strength */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Peptide Strength (Vial)</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {strength !== 'other' ? (
                <>
                  <Select value={strength} onValueChange={setStrength}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {strengthOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mg
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setStrength('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={strengthCustom}
                    onChange={(e) => setStrengthCustom(e.target.value)}
                    placeholder="Enter strength"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setStrength('10');
                      setStrengthCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>

            {/* Water Volume */}
            <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-3">
                <label className="text-amber-50 font-semibold">Bacteriostatic Water</label>
                <Info className="w-4 h-4 text-stone-500" />
              </div>
              {water !== 'other' ? (
                <>
                  <Select value={water} onValueChange={setWater}>
                    <SelectTrigger className="bg-stone-800 border-stone-600 text-amber-50 mb-3">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-stone-800 border-stone-600">
                      {waterOptions.map((opt) => (
                        <SelectItem key={opt} value={opt} className="text-amber-50">
                          {opt} mL
                        </SelectItem>
                      ))}
                      <SelectItem value="other" className="text-amber-50">
                        Other
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => setWater('other')}
                  >
                    Custom
                  </Button>
                </>
              ) : (
                <>
                  <input
                    type="number"
                    value={waterCustom}
                    onChange={(e) => setWaterCustom(e.target.value)}
                    placeholder="Enter volume"
                    className="w-full bg-stone-800 border border-stone-600 rounded px-3 py-2 text-amber-50 placeholder-stone-500 focus:outline-none focus:border-red-600 mb-3"
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600 w-full"
                    onClick={() => {
                      setWater('1.0');
                      setWaterCustom('');
                    }}
                  >
                    Use Preset
                  </Button>
                </>
              )}
            </div>
          </div>

          {/* RIGHT SIDE - RESULTS */}
          <div className="bg-stone-900/50 border border-stone-700 rounded-lg p-8 sticky top-32 h-fit">
            <h2 className="text-2xl font-bold text-amber-50 mb-8">Results</h2>

            {!isValid ? (
              <div className="text-stone-400 text-center py-12">
                <p>Enter values to calculate</p>
              </div>
            ) : (
              <div className="space-y-6">
                {/* Results Cards */}
                <div className="space-y-5">
                  {/* Draw Amount */}
                  <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                    <p className="text-stone-400 text-sm mb-2">Draw to</p>
                    <p className="text-3xl font-bold text-red-600">{drawAmount} mL</p>
                  </div>

                  {/* Draw Units */}
                  <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                    <p className="text-stone-400 text-sm mb-2">Or draw to</p>
                    <p className="text-3xl font-bold text-red-600">{drawUnits} units</p>
                    <p className="text-stone-500 text-xs mt-1">on {currentSyringeSize}mL syringe</p>
                  </div>

                  {/* Concentration */}
                  <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                    <p className="text-stone-400 text-sm mb-2">Concentration</p>
                    <p className="text-3xl font-bold text-red-600">{concentration.toFixed(2)}</p>
                    <p className="text-stone-500 text-sm mt-1">mg/mL</p>
                  </div>

                  {/* Doses in Vial */}
                  <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700">
                    <p className="text-stone-400 text-sm mb-2">Doses in vial</p>
                    <p className="text-3xl font-bold text-red-600">{dosesInVial}</p>
                  </div>

                  {/* Warning if draw exceeds water volume */}
                  {parseFloat(drawAmount) > currentWater && (
                    <div className="bg-red-600/20 border border-red-600/50 rounded-lg p-4 text-red-400 text-sm mt-6">
                      ⚠️ Draw amount exceeds available reconstituted volume. Adjust dose or add more water.
                    </div>
                  )}

                  {/* Warning if draw exceeds syringe capacity */}
                  {exceedsSyringeCapacity && (
                    <div className="bg-yellow-600/20 border border-yellow-600/50 rounded-lg p-4 text-yellow-400 text-sm mt-6">
                      ⚠️ Draw amount ({drawAmount} mL) exceeds your {currentSyringeSize}mL syringe capacity. Consider using a larger syringe or splitting into multiple draws.
                    </div>
                  )}

                  {/* Action Buttons */}
                  <div className="space-y-3 mt-8 pt-6 border-t border-stone-700">
                    <div className="flex gap-3">
                      <Button
                        onClick={handleReset}
                        variant="outline"
                        className="flex-1 border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600"
                      >
                        <RotateCcw className="w-4 h-4 mr-2" />
                        Reset
                      </Button>
                      <Button 
                        onClick={handleDownload}
                        className="flex-1 bg-red-600 hover:bg-red-700 text-amber-50"
                      >
                        Download Results
                      </Button>
                    </div>
                    <Button
                      onClick={() => setShowQRCode(true)}
                      variant="outline"
                      className="w-full border-stone-600 text-stone-400 hover:text-red-600 hover:border-red-600"
                    >
                      <QrCode className="w-4 h-4 mr-2" />
                      Generate QR Code for Phone
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Syringe Visualization */}
      {isValid && (
        <div className="max-w-6xl mx-auto px-4 mt-12">
          <div className="bg-stone-800/50 rounded-lg p-6 border border-stone-700 overflow-x-auto">
            <div className="flex items-center justify-between mb-4">
              <p className="text-stone-400 text-sm font-semibold">
                Syringe Markings ({currentSyringeSize}mL / {totalUnits} units)
              </p>
              <div className="flex items-center gap-2 text-xs text-stone-500">
                <Syringe className="w-4 h-4" />
                <span>{currentSyringeSize}mL syringe selected</span>
              </div>
            </div>
            <svg viewBox="0 0 1100 120" className="w-full h-40" style={{ minWidth: '900px' }}>
              {/* Syringe barrel */}
              <rect x="50" y="30" width="1000" height="60" rx="8" fill="none" stroke="currentColor" strokeWidth="3" className="text-red-600" />

              {/* Fluid fill animation */}
              <defs>
                <linearGradient id="fluidGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" stopColor="rgba(220, 38, 38, 0.5)" />
                  <stop offset="50%" stopColor="rgba(239, 68, 68, 0.6)" />
                  <stop offset="100%" stopColor="rgba(220, 38, 38, 0.7)" />
                </linearGradient>
                <filter id="fluidShadow" x="-50%" y="-50%" width="200%" height="200%">
                  <feGaussianBlur in="SourceGraphic" stdDeviation="1" />
                </filter>
              </defs>

              {/* Fluid fill with wave effect */}
              <motion.g>
                {/* Main fluid body */}
                <motion.rect
                  x="50"
                  y="30"
                  width={Math.min(1000, (parseFloat(drawUnits) / totalUnits) * 1000)}
                  height="60"
                  rx="4"
                  fill="url(#fluidGradient)"
                  initial={{ width: 0, opacity: 0 }}
                  animate={{ width: Math.min(1000, (parseFloat(drawUnits) / totalUnits) * 1000), opacity: 1 }}
                  transition={{ type: 'spring', stiffness: 80, damping: 20, duration: 1.2 }}
                />
                
                {/* Shimmer effect */}
                <motion.ellipse
                  cx={50 + (parseFloat(drawUnits) / totalUnits) * 500}
                  cy="40"
                  rx="80"
                  ry="15"
                  fill="rgba(255, 255, 255, 0.15)"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: [0, 0.6, 0] }}
                  transition={{ delay: 0.6, duration: 0.8 }}
                />
              </motion.g>

              {/* Major markings */}
              {majorMarkings.map((units) => (
                <g key={units}>
                  <line
                    x1={50 + (units / totalUnits) * 1000}
                    y1="10"
                    x2={50 + (units / totalUnits) * 1000}
                    y2="25"
                    stroke="currentColor"
                    strokeWidth="2"
                    className="text-red-600"
                  />
                  <text
                    x={50 + (units / totalUnits) * 1000}
                    y="8"
                    textAnchor="middle"
                    fontSize={currentSyringeSize === 3 ? "14" : "16"}
                    fontWeight="700"
                    fill="currentColor"
                    className="text-red-600"
                  >
                    {units}
                  </text>
                </g>
              ))}

              {/* Minor markings */}
              {minorMarkings.map((units) => (
                <line
                  key={`minor-${units}`}
                  x1={50 + (units / totalUnits) * 1000}
                  y1="15"
                  x2={50 + (units / totalUnits) * 1000}
                  y2="25"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  className="text-red-600"
                />
              ))}

              {/* Current draw indicator */}
              {parseFloat(drawUnits) <= totalUnits && (
                <line
                  x1={50 + (parseFloat(drawUnits) / totalUnits) * 1000}
                  y1="30"
                  x2={50 + (parseFloat(drawUnits) / totalUnits) * 1000}
                  y2="90"
                  stroke="currentColor"
                  strokeWidth="3"
                  className="text-amber-400"
                  strokeDasharray="5,5"
                />
              )}
            </svg>
            <p className="text-center text-red-600 font-bold text-lg mt-4">
              Draw to <span className="text-2xl">{drawUnits}</span> units ({drawAmount} mL) on your {currentSyringeSize}mL syringe
            </p>
          </div>

          {/* Reconstitution Steps */}
          <div className="bg-stone-800/50 rounded-lg p-5 border border-stone-700 mt-6">
            <p className="text-stone-400 text-sm font-semibold mb-3">Reconstitution Steps:</p>
            <ol className="space-y-2 text-sm text-stone-300 list-decimal list-inside">
              <li>Draw {currentWater} mL of bacteriostatic water into a syringe</li>
              <li>Inject into the vial containing {currentStrength} mg peptide</li>
              <li>Let the solution reconstitute for 5-10 minutes</li>
              <li>Using your <span className="text-red-600 font-semibold">{currentSyringeSize}mL syringe</span>, draw {drawAmount} mL ({drawUnits} units) for your {currentDose} mg dose – <Link to={createPageUrl('PeptideReconstitutionGuide')} className="text-red-600 hover:text-red-500 underline">Full Guide Here</Link></li>
            </ol>
          </div>
        </div>
      )}

      {/* Footer Info */}
      <div className="max-w-6xl mx-auto px-4 mt-16">
        <div className="bg-stone-900/30 border border-stone-700 rounded-lg p-8">
          <h3 className="text-xl font-bold text-amber-50 mb-4">How to use</h3>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 text-stone-400 text-sm">
            <div>
              <p className="font-semibold text-amber-50 mb-2">1. Select syringe size</p>
              <p>Choose the syringe you'll use (1mL, 2mL, or 3mL).</p>
            </div>
            <div>
              <p className="font-semibold text-amber-50 mb-2">2. Set your dose</p>
              <p>The amount of peptide you want to administer in milligrams.</p>
            </div>
            <div>
              <p className="font-semibold text-amber-50 mb-2">3. Enter peptide strength</p>
              <p>Total milligrams in your vial from the manufacturer.</p>
            </div>
            <div>
              <p className="font-semibold text-amber-50 mb-2">4. Choose water volume</p>
              <p>The mL of bacteriostatic water you're using for reconstitution.</p>
            </div>
          </div>
        </div>
      </div>

      {/* QR Code Modal */}
      <Dialog open={showQRCode} onOpenChange={setShowQRCode}>
        <DialogContent className="bg-stone-900 border-stone-700 max-w-md">
          <div className="text-center p-6">
            <h2 className="text-2xl font-bold text-amber-50 mb-4">
              Scan with Your Phone
            </h2>
            <p className="text-stone-400 text-sm mb-6">
              This QR code will take you to a mobile-friendly instruction page with your calculations
            </p>
            
            {/* QR Code */}
            <div className="bg-white p-6 rounded-xl inline-block mb-6">
              <QRCodeSVG
                value={generateQRCodeURL()}
                size={256}
                level="H"
                includeMargin={true}
              />
            </div>

            {/* Instructions */}
            <div className="bg-stone-800/50 border border-stone-700 rounded-lg p-4 text-left">
              <p className="text-stone-300 text-sm mb-2">📱 How to use:</p>
              <ol className="text-stone-400 text-xs space-y-1 list-decimal list-inside">
                <li>Open your phone's camera</li>
                <li>Point it at the QR code</li>
                <li>Tap the notification to open the link</li>
                <li>Follow the step-by-step instructions</li>
              </ol>
            </div>

            <Button
              onClick={() => setShowQRCode(false)}
              className="w-full mt-6 bg-red-600 hover:bg-red-700"
            >
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}